FROM golang:1.23.1-alpine AS builder

WORKDIR /app
COPY go.mod ./
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app/server ./main.go

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/server .
COPY SeatMapResponse.json .
EXPOSE 8080
CMD ["./server"]
